#!/bin/sh
#Upstream makes use of “clknetsim” to test how well “chronyd” controls the
#system clocks in various conditions. Due to “clknetsim” not being available
#in Debian, let’s use autopkgtest facility to build it in a container and
#test “chronyd” from there.

set -e

if ! dpkg-architecture -ilinux-any; then
    echo "Simulation tests supported only on Linux…"
    exit 0
fi

cd test/simulation

if [ ! -d clknetsim ]; then
    git clone https://github.com/mlichvar/clknetsim && cd clknetsim && \
        git checkout 156b8e4
fi

if [ ! -x "clknetsim" ] && [ ! -e "clknetsim.so" ]; then
    make 2>&1
fi

cd .. && ./run -i 20 -m 2
