---
include:
    - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

variables:
    # Skip the reprotest job as long as it is run as root due to problems with
    # chrony system tests.
    SALSA_CI_DISABLE_REPROTEST: 1
