#!/bin/sh

set -e

# Let chronyd poll time server(s) if a default route exists.
go_online()
{
    if ip r 2>/dev/null | grep -q '^default'; then
        chronyc -m online 'burst 4/4' > /dev/null 2>&1
    fi
}

case "$1" in
    go_online)
        go_online
        ;;

    *)
        echo "Usage: $0 {go_online}" >&2
        exit 1
        ;;
esac
