#!/bin/sh
set -e
# postinst for chrony John Hasler jhasler@debian.org 2000-2003
# Any possessor of a copy of this program may treat it as if it
# were in the public domain.  I waive all rights.

install-info --quiet --description="Set your clock from the Net" \
	     --section General "General Commands" \
             /usr/share/info/chrony.info

if [ -x /usr/bin/update-menus ] ; then 
    /usr/bin/update-menus 
fi

# If chrony.keys is the dist file generate a random passord and put it there.

if [ "`cat /etc/chrony/chrony.keys`" = "1 password_here" ] ; then
    PASSWORD=`head -c 8 /dev/urandom | tr '\0-\377' 'a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9a-zA-Z0-9@@@@####'`
    echo "1 $PASSWORD" > /etc/chrony/chrony.keys
fi

update-rc.d chrony defaults 83 >/dev/null

# If chrony.conf is the dist file figure out whether or not we are on UTC
# and put an appropriate line in chrony.conf.

if [ -f /etc/default/rcS -a -f /etc/chrony/chrony.conf ] ; then 
    if tail -1 /etc/chrony/chrony.conf | grep -q '^# POSTINSTMARKER$' ; then
	. /etc/default/rcS
	case "$UTC" in
	    no|"") echo "# rtconutc" >> /etc/chrony/chrony.conf ;;
	    yes)   echo "rtconutc" >> /etc/chrony/chrony.conf ;;
	    *)     echo "# Can't tell what your clock is set to: assuming local time." >> /etc/chrony/chrony.conf ;;
	esac
    fi
fi

invoke-rc.d chrony start
exit 0
